version: 2
formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/source/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs