AWSTemplateFormatVersion: 2010-09-09
Description: >
  AWS Data Wrangler
  Test Arena

Parameters:
  VpcId:
    Type: String
    Description: Redshift VPC ID
  SubnetId:
    Type: String
    Description: Redshift Subnet ID
  Password:
    Type: String
    Description: Redshift Password
  TestUser:
    Type: String
    Description: AWS User that will running the tests on the CLI

Resources:

  KmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/aws-data-wrangler-test-key
      TargetKeyId:
        Ref: KmsKey

  KmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "Aws Data Wrangler Test Key."
      KeyPolicy:
        Version: "2012-10-17"
        Id: "aws-data-wrangler-test-key"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal:
              AWS: !Join ["", ["arn:aws:iam::", !Ref "AWS::AccountId", ":root"]]
            Action: "kms:*"
            Resource: "*"
          - Sid: "Allow administration of the key"
            Effect: "Allow"
            Principal:
              AWS: !Join ["", ["arn:aws:iam::", !Ref "AWS::AccountId", ":user/", !Ref TestUser]]
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  RedshiftRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - redshift.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: S3GetAndList
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:Get*"
                  - "s3:List*"
                Resource:
                  - !Join ['', ['arn:aws:s3:::', !Ref Bucket]]
                  - !Join ['', ['arn:aws:s3:::', !Ref Bucket, /*]]

  RedshiftSubnetGroup:
    Type: AWS::Redshift::ClusterSubnetGroup
    Properties:
      Description: AWS Data Wrangler Test Arena - Redshift Subnet Group
      SubnetIds:
        - Ref: SubnetId

  RedshiftSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: AWS Data Wrangler Test Arena - Redshift security group

  Redshift:
    Type: AWS::Redshift::Cluster
    DependsOn:
      - RedshiftSecurityGroup
      - RedshiftSubnetGroup
      - RedshiftRole
    Properties:
      DBName: test
      MasterUsername: test
      MasterUserPassword: !Ref Password
      NodeType: dc2.large
      ClusterType: single-node
      VpcSecurityGroupIds:
        - !Ref RedshiftSecurityGroup
      ClusterSubnetGroupName: !Ref RedshiftSubnetGroup
      PubliclyAccessible: true
      Port: 5439
      IamRoles:
        - !GetAtt RedshiftRole.Arn

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Description: AWS Data Wrangler Test Arena - Glue Database

Outputs:
  BucketName:
    Value: !Ref Bucket
    Description: Name of the S3 Bucket used for tests.
  RedshiftAddress:
    Value: !GetAtt Redshift.Endpoint.Address
    Description: Redshift Password.
  RedshiftPort:
    Value: !GetAtt Redshift.Endpoint.Port
    Description: Redshift Endpoint Port.
  RedshiftPassword:
    Value: !Ref Password
    Description: Redshift Password.
  RedshiftRole:
    Value: !GetAtt RedshiftRole.Arn
    Description: Redshift IAM role.
  GlueDatabaseName:
    Value: !Ref GlueDatabase
    Description: Glue Database Name.
  KmsKeyArn:
    Value: !GetAtt KmsKey.Arn
    Description: KMS Key ARN.
