import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Mirrors the old ReadTheDocs navigation: flat top-level pages, with
// Tutorials, ADRs and the API Reference as collapsible categories.
const sidebars: SidebarsConfig = {
  docs: [
    'index',
    'about',
    'install',
    'lambda-layers',
    'scale',
    {
      type: 'category',
      label: 'Tutorials',
      link: { type: 'doc', id: 'tutorials' },
      items: [{ type: 'autogenerated', dirName: 'tutorials' }],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: { type: 'doc', id: 'api/index' },
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
  ],
};

export default sidebars;
