name: Issue Minimum Response Time
on:
  workflow_dispatch:
  schedule:
  - cron: "0 */3 * * *"
jobs:
  evaluate:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Issue Minimum Response ⏰
        uses: malachi-constant/issue-minimum-response@latest
        with:
          exempt_user_list: "github-actions[bot]"
          exempt_labels: "help wanted"
          exempt_authors: "malachi-constant,jaidisido,kukushking,cnfait"
          token: ${{secrets.GITHUB_TOKEN}}
          label: needs-triage
