name: Unlabel Assigned Issues
on:
  issues:
    types:
      - assigned
permissions:
  contents: read

jobs:
  unlabel-issue:
    permissions:
      issues: write  # for andymckay/labeler to label issues
      pull-requests: write  # for andymckay/labeler to label PRs
    runs-on: ubuntu-latest
    steps:
      - name: unlabel-issues
        uses: andymckay/labeler@master
        with:
          remove-labels: "needs-triage"
